# Generated by Django 2.0.7 on 2018-12-28 10:53

from django.db import migrations, models
import ideas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.CharField(max_length=140, validators=[ideas.validators.validate_content]),
        ),
    ]
