# Generated by Django 2.0.7 on 2019-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
